[package]
name = "aoc_utils"
version = "0.1.0"
authors = ["suppergerrie2 <contac@suppergerrie2.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
